
        DROP TABLE IF EXISTS movies;
        CREATE TABLE movies(
            movie_id INT PRIMARY KEY AUTO_INCREMENT,
            titolo VARCHAR(100),
            anno INT NOT NULL default 0,
            rating int not null default 0,
            regista VARCHAR(100)
        
        );
    INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Psycho', 1960, 97, 'Alfred Hitchcock');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Best Years of Our Lives', 1946, 97, 'William Wyler');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Right Stuff', 1983, 96, 'Philip Kaufman');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Iron Giant', 1999, 96, 'Brad Bird');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Ghostbusters', 1984, 95, 'Ivan Reitman');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Memento', 2000, 94, 'Christopher Nolan');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Saving Private Ryan', 1998, 94, 'Steven Spielberg');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Lawrence of Arabia', 1962, 94, 'David Lean');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('No Country for Old Men', 2007, 93, 'Joel Coen');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Fighting With My Family', 2019, 93, 'Stephen Merchant');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('To Catch a Thief', 1955, 92, 'Alfred Hitchcock');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Stan & Ollie', 2018, 92, 'Jon S. Baird');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Raging Bull', 1980, 92, 'Martin Scorsese');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Fighter', 2010, 91, 'David O. Russell');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Quiet Man', 1952, 91, 'John Ford');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Downfall', 2004, 90, 'Oliver Hirschbiegel');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Reds', 1981, 90, 'Warren Beatty');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Love & Mercy', 2014, 89, 'Bill Pohlad');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Tremors', 1990, 88, 'Ron Underwood');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Rain Man', 1988, 88, 'Barry Levinson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Pee-wee's Big Adventure', 1985, 88, 'Tim Burton');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('12 Monkeys', 1995, 88, 'Terry Gilliam');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Donnie Darko', 2001, 87, 'Richard Kelly');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Star Trek Beyond', 2016, 86, 'Justin Lin');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Collateral', 2004, 86, 'Michael Mann');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Sweeney Todd: The Demon Barber of Fleet Street', 2007, 86, 'Tim Burton');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Paprika', 2006, 86, 'Satoshi Kon');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Master and Commander: The Far Side of the World', 2003, 85, 'Peter Weir');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Beyond the Lights', 2014, 84, 'Gina Prince-Bythewood');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Neverending Story', 1984, 83, 'Wolfgang Petersen');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Matchstick Men', 2003, 83, 'Ridley Scott');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Goosebumps', 2015, 78, 'Rob Letterman');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Addams Family Values', 1993, 75, 'Barry Sonnenfeld');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Cape Fear', 1991, 75, 'Martin Scorsese');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Negotiator', 1998, 74, 'F. Gary Gray');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Way Back', 2010, 74, 'Peter Weir');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Curious Case of Benjamin Button', 2008, 72, 'David Fincher');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Captain Horatio Hornblower', 1951, 100, 'Raoul Walsh');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Darby O'Gill and the Little People', 1959, 100, 'Robert Stevenson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Ip Man 2', 2010, 97, 'Wilson Yip');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Zulu', 1964, 96, 'Charles De Latour');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Judgment at Nuremberg', 1961, 92, 'Stanley Kramer');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Birdman of Alcatraz', 1962, 91, 'John Frankenheimer');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Places in the Heart', 1984, 89, 'Robert Benton');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Cooley High', 1975, 89, 'Michael Schultz');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Following', 1998, 84, 'Christopher Nolan');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Mr. Majestyk', 1974, 83, 'Richard Fleischer');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Tremors 3: Back to Perfection', 2001, 80, 'Brent Maddock');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Street Fighter II: The Animated Movie', 1995, 80, 'Gisaburo Sugii');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Crossroads', 1986, 76, 'Walter Hill');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Oh, God!', 1977, 75, 'Carl Reiner');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Child's Play', 1988, 74, 'Tom Holland');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Greystoke: The Legend of Tarzan, Lord of the Apes', 1984, 73, 'Hugh Hudson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Wedding Singer', 1998, 72, 'Frank Coraci');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Cry Baby', 1990, 72, 'John Waters');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Last Exorcism', 2010, 72, 'Daniel Stamm');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Clue', 1985, 71, 'Jonathan Lynn');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Infiltrator', 2016, 71, 'Brad Furman');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('It's a Mad, Mad, Mad, Mad World', 1963, 69, 'Stanley Kramer');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Free Willy', 1993, 71, 'Simon Wincer');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Point Break', 1991, 70, 'Kathryn Bigelow');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Murder by Death', 1976, 68, 'Robert Moore');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Railway Man', 2013, 68, 'Jonathan Teplitzky');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Running Man', 1987, 67, 'Paul Michael Glaser');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('2010', 1984, 67, 'Peter Hyams');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Heroes of Telemark', 1965, 67, 'Anthony Mann');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Uptown Saturday Night', 1974, 70, 'Sidney Poitier');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The X-Files', 1998, 66, 'Rob Bowman');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Hachi: A Dog's Tale', 2009, 64, 'Lasse Hallström');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Jack Reacher', 2012, 64, 'Christopher McQuarrie');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Battle of the Bulge', 1965, 63, 'Ken Annakin');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Wood', 1999, 61, 'Rick Famuyiwa');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Allied', 2016, 60, 'Robert Zemeckis');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Tremors II: Aftershocks', 1996, 60, 'S.S. Wilson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Let's Do It Again', 1975, 60, 'Sidney Poitier');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('It's Kind of a Funny Story', 2010, 58, 'Anna Boden');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('17 Again', 2009, 57, 'Burr Steers');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Stargate', 1994, 54, 'Roland Emmerich');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('What Dreams May Come', 1998, 52, 'Vincent Ward');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Twilight Saga: Breaking Dawn Part 2', 2012, 49, 'Bill Condon');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Twilight Saga: Eclipse', 2010, 46, 'David Slade');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Overboard', 1987, 46, 'Garry Marshall');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Greatest Story Ever Told', 1965, 42, 'George Stevens');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Majestic', 2001, 42, 'Frank Darabont');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Legend', 1985, 42, 'Ridley Scott');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Pure Country', 1992, 41, 'Christopher Cain');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Mechanic', 1972, 40, 'Michael Winner');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Girl Who Believes in Miracles', 2021, 40, 'Richard Correll');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Incredible Mr. Limpet', 1964, 40, 'Arthur Lubin');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Legend of Billie Jean', 1985, 39, 'Matthew Robbins');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Corrina, Corrina', 1994, 37, 'Jessie Nelson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Memoirs of a Geisha', 2005, 36, 'Rob Marshall');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Longest Yard', 2005, 31, 'Peter Segal');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('8 Seconds', 1994, 31, 'John G. Avildsen');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Three Musketeers', 1993, 30, 'Stephen Herek');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Twilight Saga: New Moon', 2009, 28, 'Chris Weitz');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('A Walk to Remember', 2002, 29, 'Adam Shankman');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Twilight Saga: Breaking Dawn Part 1', 2011, 25, 'Bill Condon');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Patch Adams', 1998, 21, 'Tom Shadyac');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Drop Dead Fred', 1991, 11, 'Ate de Jong');
