use cyss2026;
CREATE TABLE movies (
    id SERIAL PRIMARY KEY,
    titolo VARCHAR(255) NOT NULL,
    anno INT,
    rating FLOAT,
    regista VARCHAR(255)
);
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The First Slam Dunk', (2022), 100, 'Takehiko Inoue');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Are You There God? It''s Me, Margaret.', (2023), 99, 'Kelly Fremon Craig');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('BlackBerry', (2023), 98, 'Matt Johnson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Godzilla Minus One', (2023), 98, 'Takashi Yamazaki');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Rye Lane', (2023), 98, 'Raine Allen Miller');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Fallen Leaves', (2023), 98, 'Aki Kaurismäki');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Joyland', (2022), 98, 'Saim Sadiq');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Beasts', (2022), 98, 'Rodrigo Sorogoyen');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Full Time', (2021), 98, 'Eric Gravel');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Taste of Things', (2023), 97, 'Tran Anh Hung');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Shayda', (2023), 97, 'Noora Niasari');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Teachers'' Lounge', (2023), 97, 'Ilker Çatak');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Aloners', (2021), 98, 'Hong Sung-eun');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Innocent', (2022), 98, 'Louis Garrel');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Three Musketeers: Part I - D''Artagnan', (2023), 98, 'Martin Bourboulon');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Klondike', (2022), 98, 'Maryna Er Gorbach');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Return to Seoul', (2022), 97, 'Davy Chou');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('A Thousand and One', (2023), 97, 'A.V. Rockwell');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Monster', (2023), 96, 'Hirokazu Koreeda');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Huesera: The Bone Woman', (2022), 97, 'Michelle Garza Cervera');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Fremont', (2023), 97, 'Babak Jalali');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Past Lives', (2023), 95, 'Celine Song');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Holdovers', (2023), 97, 'Alexander Payne');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Teenage Mutant Ninja Turtles: Mutant Mayhem', (2023), 95, 'Jeff Rowe');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Anatomy of a Fall', (2023), 96, 'Justine Triet');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Boy and the Heron', (2023), 97, 'Hayao Miyazaki');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Suzume', (2022), 96, 'Makoto Shinkai');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('birth/rebirth', (2023), 96, 'Laura Moss');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Wonderful Story of Henry Sugar', (2023), 96, 'Wes Anderson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('R.M.N.', (2022), 97, 'Cristian Mungiu');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Earth Mama', (2023), 97, 'Savanah Leaf');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Blue Caftan', (2022), 96, 'Maryam Touzani');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Four Daughters', (2023), 96, 'Kaouther Ben Hania');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Spider-Man: Across the Spider-Verse', (2023), 95, 'Joaquim Dos Santos');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('They Cloned Tyrone', (2023), 95, 'Juel Taylor');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Blue Jean', (2022), 95, 'Georgia Oakley');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Nimona', (2023), 92, 'Nick Bruno');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('How to Have Sex', (2023), 96, 'Molly Manning Walker');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Attachment', (2022), 95, 'Gabriel Bier Gislason');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Amanda', (2022), 95, 'Carolina Cavalli');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('John Wick: Chapter 4', (2023), 94, 'Chad Stahelski');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Talk to Me', (2023), 95, 'Danny Philippou');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('You Hurt My Feelings', (2023), 94, 'Nicole Holofcener');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Sisu', (2022), 94, 'Jalmari Helander');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Passages', (2023), 94, 'Ira Sachs');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('How to Blow Up a Pipeline', (2022), 95, 'Daniel Goldhaber');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Saint Omer', (2022), 94, 'Alice Diop');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Scrapper', (2023), 94, 'Charlotte Regan');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Smoking Causes Coughing', (2022), 94, 'Quentin Dupieux');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Night of the 12th', (2022), 94, 'Dominik Moll');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Radical', (2023), 94, 'Christopher Zalla');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Falcon Lake', (2022), 94, 'Charlotte Le Bon');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('After Love', (2020), 92, 'Aleem Khan');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Oppenheimer', (2023), 93, 'Christopher Nolan');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Air', (2023), 93, 'Ben Affleck');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('M3GAN', (2022), 93, 'Gerard Johnstone');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Poor Things', (2023), 92, 'Yorgos Lanthimos');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('American Fiction', (2023), 93, 'Cord Jefferson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Flora and Son', (2023), 93, 'John Carney');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('All of Us Strangers', (2023), 96, 'Andrew Haigh');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Reality', (2023), 94, 'Tina Satter');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Revoir Paris', (2022), 93, 'Alice Winocour');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Alcarràs', (2022), 93, 'Carla Simón');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('American Symphony', (2023), 94, 'Matthew Heineman');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Zone of Interest', (2023), 93, 'Jonathan Glazer');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Starling Girl', (2023), 92, 'Laurel Parmet');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Perfect Days', (2023), 96, 'Wim Wenders');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Juniper', (2021), 92, 'Matthew J. Saville');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Influencer', (2023), 92, 'Kurtis David Harder');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('War Pony', (2022), 92, 'Riley Keough');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Jethica', (2022), 92, 'Pete Ohs');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Dungeons & Dragons: Honor Among Thieves', (2023), 91, 'Jonathan M. Goldstein');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('May December', (2023), 90, 'Todd Haynes');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Joy Ride', (2023), 90, 'Adele Lim');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Dream Scenario', (2023), 92, 'Kristoffer Borgli');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Afire', (2023), 92, 'Christian Petzold');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('You Are So Not Invited to My Bat Mitzvah', (2023), 91, 'Sammi Cohen');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Godland', (2022), 91, 'Hlynur Pálmason');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Other People''s Children', (2022), 91, 'Rebecca Zlotowski');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Society of the Snow', (2023), 90, 'J. A. Bayona');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Chile ''76', (2022), 91, 'Manuela Martelli');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Artifice Girl', (2022), 91, 'Franklin Ritch');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Unknown Country', (2022), 92, 'Morrisa Maltz');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Leonor Will Never Die', (2022), 91, 'Martika Ramirez Escobar');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Origin of Evil', (2022), 91, 'Sébastien Marnier');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Bottoms', (2023), 90, 'Emma Seligman');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Polite Society', (2023), 90, 'Nida Manzoor');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Brooklyn 45', (2023), 90, 'Ted Geoghegan');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Dreamin'' Wild', (2022), 90, 'Bill Pohlad');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('All Dirt Roads Taste of Salt', (2023), 89, 'Raven Jackson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Cow Who Sang a Song Into the Future', (2022), 90, 'Francisca Alegría');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('You Can Live Forever', (2022), 90, 'Sarah Watts');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Sanctuary', (2022), 88, 'Zachary Wigon');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('A Million Miles Away', (2023), 89, 'Alejandra Márquez Abella');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Aporia', (2023), 89, 'Jared Moshe');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Aristotle and Dante Discover the Secrets of the Universe', (2022), 90, 'Aitch Alberto');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Mutt', (2023), 89, 'Vuk Lungulov-Klotz');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Barbie', (2023), 88, 'Greta Gerwig');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Creed III', (2023), 88, 'Michael B. Jordan');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Iron Claw', (2023), 89, 'Sean Durkin');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Showing Up', (2022), 88, 'Kelly Reichardt');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Missing', (2023), 88, 'Will Merrick');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Royal Hotel', (2023), 89, 'Kitty Green');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Emily', (2022), 88, 'Frances O''Connor');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Tori and Lokita', (2022), 88, 'Jean-Pierre Dardenne');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Sick of Myself', (2022), 88, 'Kristoffer Borgli');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Il buco', (2021), 88, 'Michelangelo Frammartino');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Infinity Pool', (2023), 87, 'Brandon Cronenberg');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Blackening', (2022), 87, 'Tim Story');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Color Purple', (2023), 82, 'Blitz Bazawule');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Totally Killer', (2023), 87, 'Nahnatchka Khan');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Pacifiction', (2022), 87, 'Albert Serra');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Sick', (2022), 87, 'John Hyams');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Brother', (2022), 87, 'Clement Virgo');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Theater Camp', (2023), 86, 'Molly Gordon');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Of an Age', (2022), 86, 'Goran Stolevski');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Five Devils', (2022), 86, 'Léa Mysius');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Wrath of Becky', (2023), 86, 'Matt Angel');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Killer', (2023), 85, 'David Fincher');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Fair Play', (2023), 85, 'Chloe Domont');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Eileen', (2023), 83, 'William Oldroyd');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Nyad', (2023), 85, 'Elizabeth Chai Vasarhelyi');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Suitable Flesh', (2023), 85, 'Joe Lynch');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Angry Black Girl and Her Monster', (2023), 85, 'Bomani J. Story');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Cairo Conspiracy', (2022), 85, 'Tarik Saleh');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Wonka', (2023), 82, 'Paul King');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Evil Dead Rise', (2023), 84, 'Lee Cronin');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Dumb Money', (2023), 84, 'Craig Gillespie');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Rustin', (2023), 84, 'George C. Wolfe');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Thanksgiving', (2023), 84, 'Eli Roth');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Shortcomings', (2023), 85, 'Randall Park');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Jules', (2023), 85, 'Marc Turtletaub');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Guardians of the Galaxy Vol. 3', (2023), 82, 'James Gunn');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Priscilla', (2023), 84, 'Sofia Coppola');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Tetris', (2023), 81, 'Jon S. Baird');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('El Conde', (2023), 82, 'Pablo Larraín');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('No One Will Save You', (2023), 82, 'Brian Duffield');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Linoleum', (2022), 82, 'Colin West');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Persian Version', (2023), 83, 'Maryam Keshavarz');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Rotting in the Sun', (2023), 82, 'Sebastian Silva');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Monica', (2022), 84, 'Andrea Pallaoro');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Maestro', (2023), 79, 'Bradley Cooper');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Leo', (2023), 82, 'Robert Marianetti');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Perpetrator', (2023), 82, 'Jennifer Reeder');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Saw X', (2023), 80, 'Kevin Greutert');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Biosphere', (2022), 80, 'Mel Eslyn');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Quiz Lady', (2023), 81, 'Jessica Yu');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Extraction 2', (2023), 79, 'Sam Hargrave');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Chicken Run: Dawn of the Nugget', (2023), 81, 'Sam Fell');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Enys Men', (2022), 79, 'Mark Jenkin');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Origin', (2023), 81, 'Ava DuVernay');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Between Two Worlds', (2021), 79, 'Emmanuel Carrère');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Scarlet', (2022), 79, 'Pietro Marcello');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Blue Beetle', (2023), 78, 'Angel Manuel Soto');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Plane', (2023), 78, 'Jean-François Richet');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Chevalier', (2022), 77, 'Stephen Williams');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Lost King', (2022), 77, 'Stephen Frears');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Scream VI', (2023), 76, 'Matt Bettinelli-Olpin');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('A Haunting in Venice', (2023), 76, 'Kenneth Branagh');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Red, White & Royal Blue', (2023), 76, 'Matthew Lopez');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Lesson', (2023), 76, 'Alice Troughton');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Sitting in Bars with Cake', (2023), 75, 'Trish Sie');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Asteroid City', (2023), 75, 'Wes Anderson');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Leave the World Behind', (2023), 75, 'Sam Esmail');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Strange Way of Life', (2023), 76, 'Pedro Almodóvar');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Moving On', (2022), 75, 'Paul Weitz');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Offering', (2022), 74, 'Oliver Park');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('The Inventor', (2023), 75, 'Jim Capobianco');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Elemental', (2023), 73, 'Peter Sohn');
INSERT INTO movies (titolo, anno, rating, regista) VALUES ('Medusa Deluxe', (2022), 72, 'Thomas Hardiman');
